### ISSUE TITLE
Out of bounds while loading a mesh

### ISSUE THREAD

**Issue by lauris47** [alphazolam/fmt_RE_MESH-Noesis-Plugin#27]
Hi,
Mesh from the Street fighter 6 fails to import:
_REtool\re_chunk_000\natives\stm\product\environment\stage\resource\ess\ess4000_00\ess4000_00_22.mesh.230110883_
with error:
![image](https://github.com/user-attachments/assets/67eb1412-9bb1-418f-98dc-fcd0f78f6a73)
_Position buffer would have been read out of bounds by provided indices._
[ess4000_00_22.mesh.zip](https://github.com/user-attachments/files/16377083/ess4000_00_22.mesh.zip)

**Comment by alphazolam** [comment]
This is interesting, the mesh seems to use integers instead of shorts for storing its face indexes. I found the flag for it (I think) and made Noesis read the mesh; I'm going to try and reverse this to see if you can export a mod with ints. That would enable meshes with up to 4 billion verts (theoretically)

**Comment by lauris47** [comment]
@alphazolam Hey, is this fixed ? :}
